config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  # get '/restaurants/top', to: 'restaurants#top'
  # get '/restaurants/:id/chef', to: 'restaurants#chef'

  # get '/reviews/new', to: 'reviews#new'
  # post '/reviews', to: 'reviews#create'

  # DELETE /reviews/:id
  resources :reviews, only: [:destroy]

  resources :restaurants do
    resources :reviews, only: [:new, :create]

    collection do
      get :top # GET /restaurants/top, to: 'restaurants#top'
      get :shitty # GET /restaurants/shitty, to: 'restaurants#shitty'
    end

    member do
      get :chef # GET /restaurants/:id/chef, to: 'restaurants#chef'
      get :schedule # GET /restaurants/:id/schedule, to: 'restaurants#schedule'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy # @restaurant.reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # because we have restaurant_id FK
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy chef]

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  # GET /restaurants/:id/chef
  def chef
    @chef = @restaurant.chef_name
  end

  # GET /restaurants
  # GET /restaurants?rating=?
  def index
    rating = params[:rating]

    @restaurants = if rating
                     Restaurant.where(rating:)
                   else
                     Restaurant.all
                   end
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy!
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed.",
                                 status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, except: [:destroy]

  # GET /restaurants/:restaurant_id/reviews/new
  def new
    @review = Review.new
  end

  # POST /restaurants/:restaurant_id/reviews
  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    redirect_to restaurant_path(@review.restaurant)
  end

  # DELETE /reviews/:id
  def destroy
    @review = Review.find(params[:id])
    @review.destroy # @review is gone from the DB but still available in code

    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeyondCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <h1>
    <%= restaurant.name %>
  </h1>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= restaurant.rating %>
  </p>

</div>

app/views/restaurants/chef.html.erb
<h1>Chef details for
  <%= @restaurant.name %></h1>
<h2><%= @chef %></h2>

<%= link_to "Back to restaurant", restaurant_path(@restaurant) %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Check the top restaurants in your area!",
top_restaurants_path,
class: "btn btn-outline-secondary" %>

<%= simple_form_for '', method: :get do |f| %>
  <%= f.input :rating, label: false %>
  <%= f.submit "FILTER!", name: nil %>
<% end %>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<h3>User reviews
  <%= link_to "Add new",
  new_restaurant_review_path(@restaurant),
  class: "btn btn-primary btn-sm" %></h3>

<ul>
  <% @restaurant.reviews.order(created_at: :desc).each do |review| %>
    <li><%= review.created_at.to_formatted_s(:short) %>
      –
      <%= review.content %><%= link_to "DESTROY!",
      review_path(review),
      data: {
        turbo_method: :delete,
      },
      class: "text-danger" %></li>
  <% end %>
</ul>

<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %>
  |
  <%= link_to "Back to restaurants", restaurants_path %>
  |
  <%= link_to "Chef defails", chef_restaurant_path(@restaurant) %>

  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/restaurants/top.html.erb
<h1>Top Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h1>Add new review about
  <%= @restaurant.name %></h1>
<!-- tries to POST to /reviews --> <!-- POST
/restaurants/:restaurant_id/reviews -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%#= f.association :restaurant %>
  <%= f.submit %>
<% end %>